# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aifw", "0003_aiusagelog_tenant_object_metadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiactiontype",
            options={"verbose_name": "AI Action Type", "verbose_name_plural": "AI Action Types"},
        ),
        migrations.AlterModelOptions(
            name="aiusagelog",
            options={"ordering": ["-created_at"], "verbose_name": "AI Usage Log", "verbose_name_plural": "AI Usage Logs"},
        ),
        migrations.AlterModelOptions(
            name="llmmodel",
            options={"verbose_name": "LLM Model", "verbose_name_plural": "LLM Models"},
        ),
        migrations.AlterModelOptions(
            name="llmprovider",
            options={"verbose_name": "LLM Provider", "verbose_name_plural": "LLM Providers"},
        ),
        migrations.AlterField(
            model_name="aiactiontype",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="aiusagelog",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="llmprovider",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
