# Generated by Django 5.0.14 on 2026-03-05 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifw', '0005_quality_level_routing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchemaSource',
        ),
        migrations.AlterModelOptions(
            name='aiactiontype',
            options={'ordering': ['code', 'quality_level', 'priority'], 'verbose_name': 'AI Action Type', 'verbose_name_plural': 'AI Action Types'},
        ),
        migrations.AlterModelOptions(
            name='aiusagelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Usage Log', 'verbose_name_plural': 'AI Usage Logs'},
        ),
        migrations.AlterModelOptions(
            name='llmmodel',
            options={'verbose_name': 'LLM Model', 'verbose_name_plural': 'LLM Models'},
        ),
        migrations.AlterModelOptions(
            name='llmprovider',
            options={'verbose_name': 'LLM Provider', 'verbose_name_plural': 'LLM Providers'},
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='aifw_usage__quality_993f55_idx',
            old_name='idx_usagelog_ql_created',
        ),
        migrations.AlterField(
            model_name='aiactiontype',
            name='code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aiactiontype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiactiontype',
            name='priority',
            field=models.CharField(blank=True, help_text="'fast'|'balanced'|'quality' or NULL (catch-all). Enforced by DB CHECK constraint chk_aiaction_priority.", max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='aiactiontype',
            name='prompt_template_key',
            field=models.CharField(blank=True, help_text="promptfw template key e.g. 'story_writing_premium'. NULL = caller uses action code as fallback. Convention: <action_code>[_economy|_balanced|_premium]. aifw never imports promptfw — this is a plain string.", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='aiactiontype',
            name='quality_level',
            field=models.IntegerField(blank=True, help_text='Quality band (1–9) or NULL (catch-all for any quality_level). 1–3=Economy, 4–6=Balanced, 7–9=Premium. Use QualityLevel constants: ECONOMY=2, BALANCED=5, PREMIUM=8.', null=True),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, help_text="Opaque reference to the domain object (e.g. 'chapter:42').", max_length=200),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='quality_level',
            field=models.IntegerField(blank=True, db_index=True, help_text='Quality level of the request (1–9). NULL for legacy entries created before 0.6.0. Dedicated column — never use join to AIActionType for cost analytics.', null=True),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tierqualitymapping',
            name='quality_level',
            field=models.IntegerField(help_text='Quality level 1–9 assigned to this tier. Use QualityLevel constants: ECONOMY=2, BALANCED=5, PREMIUM=8.'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['action_type', 'created_at'], name='aifw_usage__action__847fa4_idx'),
        ),
    ]
