# Generated by Django 5.2.11 on 2026-06-23 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aifw", "0009_aiusagelog_privacy_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusagelog",
            name="privacy_mode",
            field=models.CharField(
                db_index=True,
                default="full",
                help_text="Privacy policy applied at write time (issue #8): 'full' (raw) | 'pseudonymous' (HMAC user_hash + topic) | 'anonymous' (tenant + day_bucket only). Set automatically by aifw.privacy from AIFW_PRIVACY_MODE.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="models",
                to="aifw.llmprovider",
            ),
        ),
        migrations.AlterField(
            model_name="tierqualitymapping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tierqualitymapping",
            name="tier",
            field=models.CharField(
                help_text="Subscription tier name e.g. 'premium', 'pro', 'freemium'.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="aiactiontype",
            index=models.Index(fields=["code", "is_active"], name="idx_aiaction_code_active"),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["quality_level", "created_at"], name="aifw_usage__quality_993f55_idx"
            ),
        ),
    ]
